- hosts: all
  become: yes
  tasks:
    - name: Install packages using apt
      ansible.builtin.apt:
        pkg: 
          - docker.io
          - ansible
        state: latest
        update_cache: yes
        cache_valid_time: 3600 
    
    - name: Enable and restart docker
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Append docker to thijs user
      ansible.builtin.user:
        name: thijs
        shell: /bin/bash
        groups: docker
        append: yes
